version: "3"

volumes:
  db: {}

services:
  db:
    restart: unless-stopped
    hostname: db
    container_name: db
    image: mysql:8.3.0
    volumes:
      - ./.mysql.prod:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: common
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"

  api:
    hostname: api
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    volumes:
      - ./apps/api:/api
    environment:
      COMMAND: "start"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - db

  web:
    hostname: "web"
    container_name: "web"
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    volumes:
      - ./apps/web:/web
    environment:
      COMMAND: "start"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - "api"
